import React, { useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './styles.css';

const portals = [
  ['admin','Admin','System control center','Users, roles, portal access, integrations, tenant controls, and global settings.'],
  ['sales','Sales Portal','Sales pipeline','Leads, opportunities, customers, handoff notes, quote requests, and follow-up.'],
  ['estimating','Estimating Portal','Estimating workflow','Estimate intake, scope builder, cost build, margin review, quote generation, and bid handoff.'],
  ['projects','Projects Portal','Project execution','Contracted jobs, engineering, material, fabrication, delivery, erection schedule, punch, and closeout.'],
  ['planning','Planning Portal','Operations planning','Job readiness, resources, schedule blockers, handoffs, and production/field readiness.'],
  ['accounting','Accounting Portal','Financial control','Billing, insurance, invoices, SOV, payments, AR, AP, change order billing, and reporting.'],
  ['purchasing','Purchasing Portal','Procurement and POs','Purchase orders, vendor assignment, material purchasing, approvals, due dates, and receiving.'],
  ['hr','HR Portal','Human resources','Salary employee records, PTO, handbook, HR support, onboarding, and training modules. No time clock.'],
  ['contacts','Contacts / CRM','Relationships','Companies, customer contacts, vendor contacts, contractor contacts, project contacts, and account history.'],
  ['vendor','Vendor Portal','Outside vendors','Assigned packages, vendor-facing PO visibility, due dates, upload slots, and packet status.'],
  ['customer','Customer Portal','Outside customers','Approved project status, documents, quotes, contracts, change orders, payments, approvals, and uploads.'],
  ['employee','Employee Self-Service','Employee access','Personal profile, PTO requests, handbook acknowledgements, training assignments, and employee documents.']
];
const baseProfiles = [
  { id:'admin', name:'Admin / Owner', email:'admin@steelcraft.local', portals: portals.map(([id])=>id) },
  { id:'accounting', name:'Accounting', email:'accounting@steelcraft.local', portals:['accounting','purchasing','contacts','employee'] },
  { id:'purchasing', name:'Purchasing', email:'purchasing@steelcraft.local', portals:['purchasing','accounting','projects','planning','vendor','contacts','employee'] },
  { id:'projects', name:'Projects', email:'projects@steelcraft.local', portals:['projects','planning','sales','estimating','customer','contacts','employee'] },
  { id:'sales', name:'Sales', email:'sales@steelcraft.local', portals:['sales','estimating','contacts','customer','employee'] },
  { id:'employee', name:'Employee', email:'employee@steelcraft.local', portals:['employee'] },
  { id:'vendor', name:'Vendor User', email:'vendor@steelcraft.local', portals:['vendor'] },
  { id:'customer', name:'Customer User', email:'customer@steelcraft.local', portals:['customer'] }
];
const brandDefaults = { tenantName:'Steel Craft', logoText:'Steel Craft', logoSubtext:'Operations Portal', logoUrl:'', navLayout:'dock-left', uiTheme:'dark-industrial', primaryColor:'#0f1014', accentColor:'#9f3d42', panelColor:'#151519', pageBgColor:'#030303', surfaceColor:'#141418', surfaceAltColor:'#1e1e24', textColor:'#f6f0ea', mutedTextColor:'#b7aaa3', borderColor:'#343036', buttonColor:'#9f3d42', buttonTextColor:'#ffffff', successColor:'#3fb56f', warningColor:'#d99b34', dangerColor:'#d34b4b', infoColor:'#4c9bd9', sidebarColor:'#111116', topbarColor:'#111116', cardColor:'#151519', inputColor:'#202026', shadowColor:'#000000' };
const navLayouts = [['dock-left','Left dock'],['dock-right','Right dock'],['top-rail','Top rail'],['bottom-dock','Bottom dock'],['left-sidebar','Left sidebar'],['right-sidebar','Right sidebar'],['command-center','Command center']];
const themeOptions = ['dark-industrial','light-steel','clean-saas','field-ops','executive','glass','high-contrast'];
const colorKeys = ['primaryColor','accentColor','panelColor','pageBgColor','surfaceColor','surfaceAltColor','textColor','mutedTextColor','borderColor','buttonColor','buttonTextColor','successColor','warningColor','dangerColor','infoColor','sidebarColor','topbarColor','cardColor','inputColor','shadowColor'];
function loadBrand(){ try { return { ...brandDefaults, ...(JSON.parse(localStorage.getItem('steelcraft_brand_controls_v1')) || {}) }; } catch { return brandDefaults; } }
function saveBrand(next){ localStorage.setItem('steelcraft_brand_controls_v1', JSON.stringify(next)); }
function styleVars(b){ return { '--brand-accent':b.accentColor, '--page-bg':b.pageBgColor, '--surface':b.surfaceColor, '--surface-alt':b.surfaceAltColor, '--text':b.textColor, '--muted':b.mutedTextColor, '--line':b.borderColor, '--button':b.buttonColor, '--button-text':b.buttonTextColor, '--sidebar':b.sidebarColor, '--topbar':b.topbarColor, '--card':b.cardColor, '--input':b.inputColor, '--shadow':b.shadowColor }; }
function meta(id){ return portals.find(([pid])=>pid===id) || portals[0]; }
function BrandMark({brand}){ return <div className="brand">{brand.logoUrl ? <img className="brand-logo-img" src={brand.logoUrl} alt={`${brand.logoText} logo`} /> : <div className="mark"><span>S</span><span className="beam">C</span><span>B</span></div>}<div><strong>{brand.logoText}</strong><small>{brand.logoSubtext}</small></div></div>; }
function DockButton({onClick}){ return <button className="dock-trigger" onClick={onClick} aria-label="Open portal dock"><span></span><span></span><span></span></button>; }
function PortalList({items, active, open}){ return <div className="nav-list">{items.map(([id,title,kind,desc])=><button key={id} className={active===id?'active':''} onClick={()=>open(id)}><strong>{title}</strong><span>{kind}</span><small>{desc}</small></button>)}</div>; }
function Shell({brand,user,active,setActive,signOut,children}){ const [open,setOpen]=useState(false); const allowed=portals.filter(([id])=>user.portals.includes(id)); const current=meta(active); const permanent=['top-rail','bottom-dock','left-sidebar','right-sidebar'].includes(brand.navLayout); const choose=id=>{setActive(id);setOpen(false)}; return <main className={`dashboard layout-${brand.navLayout} theme-${brand.uiTheme}`} style={styleVars(brand)}><header className="erp-topbar panel"><BrandMark brand={brand}/><div className="topbar-meta"><span>Signed in as</span><strong>{user.name}</strong><small>{user.portals.length} portals available</small></div>{brand.navLayout==='top-rail'&&<PortalList items={allowed} active={active} open={choose}/>}<div className="current-portal"><span>Current portal</span><strong>{current[1]}</strong></div><button className="sign-out" onClick={signOut}>Sign out</button></header>{brand.navLayout!=='top-rail'&&<DockButton onClick={()=>setOpen(true)}/>} {(brand.navLayout==='left-sidebar'||brand.navLayout==='right-sidebar')&&<aside className="persistent-sidebar panel"><p className="eyebrow">Portal navigation</p><PortalList items={allowed} active={active} open={choose}/></aside>} {brand.navLayout==='bottom-dock'&&<nav className="bottom-nav panel"><PortalList items={allowed} active={active} open={choose}/></nav>}<div className={`dock-backdrop ${open?'open':''}`} onClick={()=>setOpen(false)}/>{!permanent&&<aside className={`portal-dock panel ${open?'open':''}`}><div className="dock-head"><div><p className="eyebrow">Portal dock</p><h2>Available workspaces</h2></div><button onClick={()=>setOpen(false)}>×</button></div><PortalList items={allowed} active={active} open={choose}/></aside>}<section className="workspace">{children}</section></main> }
function Header({id}){ const [,title,kind,desc]=meta(id); return <header className="workspace-header panel"><div><p className="eyebrow">{kind}</p><h1>{title}</h1><p>{desc}</p></div><div className="live-badge">Backend connected</div></header> }
function Portal({id}){ const rows = id==='projects' ? [['Erection schedule','Crew planning, erection dates, field readiness, and conflicts.','Projects'],['Project dashboard','Contracted jobs and project status.','Projects']] : [['Workspace','Role-based ERP lane.','Ready'],['Next build','Forms, tables, records, and workflow actions.','Scaffold']]; return <><Header id={id}/><div className="workspace-grid"><article className="feature panel large"><p className="eyebrow">ERP work portal</p><h2>{meta(id)[1]}</h2><p>{meta(id)[3]}</p>{id==='projects'&&<div className="notice">Erection Schedule lives under Projects.</div>}</article><RecordList title="Portal map" rows={rows}/></div></> }
function RecordList({title,rows}){ return <article className="feature panel"><h2>{title}</h2><div className="data-rows">{rows.map(([a,b,c])=><div className="data-row" key={a}><div><strong>{a}</strong><span>{b}</span></div><b>{c}</b></div>)}</div></article> }
function Admin({profiles,setProfiles}){ const [selected,setSelected]=useState(profiles[0].id); const profile=profiles.find(p=>p.id===selected)||profiles[0]; const toggle=pid=>setProfiles(all=>all.map(p=>p.id!==profile.id?p:{...p, portals:p.portals.includes(pid)?p.portals.filter(x=>x!==pid):[...p.portals,pid]})); return <><Header id="admin"/><div className="workspace-grid"><article className="feature panel access-manager"><p className="eyebrow">Live admin permissions</p><h2>Control who sees what</h2><label>Role / user<select value={selected} onChange={e=>setSelected(e.target.value)}>{profiles.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><div className="portal-permission-grid">{portals.map(([id,title,kind])=><label className="permission-toggle" key={id}><input type="checkbox" checked={profile.portals.includes(id)} onChange={()=>toggle(id)}/><span><strong>{title}</strong><small>{kind}</small></span></label>)}</div></article><RecordList title="Current access rules" rows={profiles.map(p=>[p.name,p.email,p.portals.map(id=>meta(id)[1]).join(', ')])}/></div></> }
function Auth({brand,profiles,onSignIn}){ const [email,setEmail]=useState(''); const [secret,setSecret]=useState(''); const profile=profiles.find(p=>p.email.toLowerCase()===email.toLowerCase()); return <main className={`landing-dark auth-page theme-${brand.uiTheme}`} style={styleVars(brand)}><section className="landing-card panel auth-only"><BrandMark brand={brand}/><p className="eyebrow">Secure authentication</p><h1>{brand.logoText} ERP Login</h1><p>Sign in to continue. Portal access is assigned by the administrator after authentication.</p><label>Email<input value={email} onChange={e=>setEmail(e.target.value)} placeholder="name@company.com"/></label><label>Password<input type="password" value={secret} onChange={e=>setSecret(e.target.value)} placeholder="Password"/></label><button className="auth-submit" onClick={()=>onSignIn(profile||profiles[0])}>Sign in</button></section></main> }
function BrandControls(){ const [brand,setBrand]=useState(loadBrand); const update=(k,v)=>{const next={...brand,[k]:v};setBrand(next);saveBrand(next)}; const upload=e=>{const file=e.target.files?.[0]; if(!file)return; const reader=new FileReader(); reader.onload=()=>update('logoUrl', reader.result); reader.readAsDataURL(file);}; return <main className={`dashboard brand-controls layout-${brand.navLayout} theme-${brand.uiTheme}`} style={styleVars(brand)}><section className="workspace solo"><header className="workspace-header panel"><div><p className="eyebrow">Hidden /brand controls</p><h1>White-label Design Studio</h1><p>Upload a logo, choose navigation behavior, choose a theme, and customize the ERP color system.</p></div></header><div className="brand-studio-grid"><article className="feature panel"><h2>Logo and identity</h2><BrandMark brand={brand}/><label>Upload logo<input type="file" accept="image/*" onChange={upload}/></label><label>Logo URL<input value={brand.logoUrl} onChange={e=>update('logoUrl',e.target.value)} placeholder="https://..."/></label><label>Logo text<input value={brand.logoText} onChange={e=>update('logoText',e.target.value)}/></label><label>Logo subtext<input value={brand.logoSubtext} onChange={e=>update('logoSubtext',e.target.value)}/></label>{brand.logoUrl&&<button onClick={()=>update('logoUrl','')}>Remove uploaded logo</button>}</article><article className="feature panel"><h2>Navigation formats</h2><div className="choice-grid">{navLayouts.map(([id,label])=><button key={id} className={brand.navLayout===id?'active':''} onClick={()=>update('navLayout',id)}><strong>{label}</strong></button>)}</div></article><article className="feature panel"><h2>UI / UX themes</h2><div className="choice-grid">{themeOptions.map(t=><button key={t} className={brand.uiTheme===t?'active':''} onClick={()=>update('uiTheme',t)}><strong>{t}</strong></button>)}</div></article><article className="feature panel color-panel"><h2>20-color system</h2><div className="color-grid">{colorKeys.map(k=><label key={k}>{k}<input type="color" value={brand[k]} onChange={e=>update(k,e.target.value)}/></label>)}</div></article></div></section></main> }
function App(){ const [profiles,setProfiles]=useState(baseProfiles); const [userId,setUserId]=useState(null); const [active,setActive]=useState('admin'); const brand=useMemo(loadBrand,[]); const user=profiles.find(p=>p.id===userId); const safe=user?.portals.includes(active)?active:user?.portals[0]||'admin'; if(location.pathname.replace(/\/$/,'')==='/brand') return <BrandControls/>; if(!user) return <Auth brand={brand} profiles={profiles} onSignIn={p=>{setUserId(p.id);setActive(p.portals[0])}}/>; return <Shell brand={brand} user={user} active={safe} setActive={setActive} signOut={()=>setUserId(null)}>{safe==='admin'?<Admin profiles={profiles} setProfiles={setProfiles}/>:<Portal id={safe}/>}</Shell> }

createRoot(document.getElementById('root')).render(<App/>);
